name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7  # Escolha a versão do Ruby adequada ao seu projeto
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build Jekyll
        run: |
          bundle exec jekyll build
          echo "www.example.com" > _site/CNAME  # Substitua pelo seu domínio personalizado, se aplicável
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
